# Generated by Django 5.0.4 on 2024-04-22 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tikets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city1', models.CharField(max_length=255)),
                ('city2', models.CharField(max_length=255)),
                ('cost', models.FloatField(default=0)),
                ('company', models.CharField(max_length=255)),
                ('depar_date', models.DateTimeField(default=0)),
                ('depar_time', models.DateTimeField(default=0)),
                ('Arrival_date', models.DateTimeField(default=0)),
                ('Arrival_time', models.DateTimeField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('Acc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviato.account')),
                ('Sec_tic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aviato.tikets')),
            ],
        ),
    ]
