# Generated by Django 5.0.4 on 2024-04-24 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0005_remove_tikets_acc_id_remove_tikets_sec_tic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('cost', models.FloatField(default=0)),
                ('mini_descrip', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('raiting', models.IntegerField(default=0)),
                ('arrival_date', models.DateField(default=None)),
                ('date_departure', models.DateField(default=None)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='buy_ticket',
            name='BackTic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_tickets', to='aviato.tikets'),
        ),
        migrations.AddField(
            model_name='buy_ticket',
            name='HotelNUM',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='buy_ticket',
            name='TicNUM',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buy_ticket',
            name='Tikets_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_tickets', to='aviato.tikets'),
        ),
        migrations.CreateModel(
            name='HotelsNUM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('cost', models.FloatField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviato.hotels')),
            ],
        ),
        migrations.AddField(
            model_name='buy_ticket',
            name='hotelId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aviato.hotelsnum'),
        ),
    ]
