# Generated by Django 5.0.4 on 2024-04-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tikets',
            name='Arrival_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tikets',
            name='Arrival_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tikets',
            name='depar_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tikets',
            name='depar_time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
