# Generated by Django 5.0.4 on 2024-04-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0008_alter_tikets_arrival_date_alter_tikets_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='arrival_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='date_departure',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
