# Generated by Django 5.0.4 on 2024-04-25 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0009_alter_hotels_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_ticket',
            name='Per_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviato.account', unique=True),
        ),
    ]
