# Generated by Django 5.0.4 on 2024-04-26 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviato', '0010_alter_buy_ticket_per_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_ticket',
            name='Per_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aviato.account'),
        ),
    ]
